// Date: 2015-03-25 3:51:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.pdogmuncher.zombieapocalypse.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class CuteOcelot extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer head;
    ModelRenderer nose;
    ModelRenderer leftear;
    ModelRenderer rightear;
    ModelRenderer backfeetleft;
    ModelRenderer backfeetright;
    ModelRenderer frontLeftPaw;
    ModelRenderer frontRightPaw;
    ModelRenderer tail1;
    ModelRenderer tail2;
    ModelRenderer Fish;
  
  public CuteOcelot()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      body = new ModelRenderer(this, 20, 0);
      body.addBox(-2F, -14F, -3F, 4, 14, 6);
      body.setRotationPoint(0F, 12F, -2F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, -0.1047198F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-2.5F, -2F, -2.5F, 5, 4, 5);
      head.setRotationPoint(0F, -4F, -2F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, -0.2964248F, 0F, 0F);
      nose = new ModelRenderer(this, 8, 12);
      nose.addBox(-1.5F, 0F, -3.5F, 3, 2, 1);
      nose.setRotationPoint(0F, -4F, -2F);
      nose.setTextureSize(128, 64);
      nose.mirror = true;
      setRotation(nose, -0.2964267F, 0F, 0F);
      leftear = new ModelRenderer(this, 8, 9);
      leftear.mirror = true;
      leftear.addBox(-2F, -3F, 0.5F, 1, 1, 2);
      leftear.setRotationPoint(0F, -4F, -2F);
      leftear.setTextureSize(128, 64);
      leftear.mirror = true;
      setRotation(leftear, -0.2964267F, 0F, 0F);
      leftear.mirror = false;
      rightear = new ModelRenderer(this, 8, 9);
      rightear.addBox(1F, -3F, 0.5F, 1, 1, 2);
      rightear.setRotationPoint(0F, -4F, -2F);
      rightear.setTextureSize(128, 64);
      rightear.mirror = true;
      setRotation(rightear, -0.2964267F, 0F, 0F);
      backfeetleft = new ModelRenderer(this, 0, 9);
      backfeetleft.mirror = true;
      backfeetleft.addBox(0F, 0F, -1F, 2, 6, 2);
      backfeetleft.setRotationPoint(0.2F, 10F, -2F);
      backfeetleft.setTextureSize(128, 64);
      backfeetleft.mirror = true;
      setRotation(backfeetleft, 0F, 0F, -0.074351F);
      backfeetleft.mirror = false;
      backfeetright = new ModelRenderer(this, 0, 9);
      backfeetright.addBox(-2F, 0F, -1F, 2, 6, 2);
      backfeetright.setRotationPoint(-0.2F, 10F, -2F);
      backfeetright.setTextureSize(128, 64);
      backfeetright.mirror = true;
      setRotation(backfeetright, 0F, 0F, 0.0743572F);
      frontLeftPaw = new ModelRenderer(this, 0, 16);
      frontLeftPaw.addBox(0F, -1F, -10F, 2, 2, 10);
      frontLeftPaw.setRotationPoint(1.1F, 0F, 2.1F);
      frontLeftPaw.setTextureSize(128, 64);
      frontLeftPaw.mirror = true;
      setRotation(frontLeftPaw, -0.1115358F, 0.111544F, 0F);
      frontRightPaw = new ModelRenderer(this, 0, 16);
      frontRightPaw.addBox(-2F, -1F, -10F, 2, 2, 10);
      frontRightPaw.setRotationPoint(-1.1F, 0F, 2.1F);
      frontRightPaw.setTextureSize(128, 64);
      frontRightPaw.mirror = true;
      setRotation(frontRightPaw, -0.1115358F, -0.1115358F, 0F);
      tail1 = new ModelRenderer(this, 18, 22);
      tail1.addBox(-0.5F, 0F, 0F, 1, 1, 6);
      tail1.setRotationPoint(0F, 11F, 0F);
      tail1.setTextureSize(128, 64);
      tail1.mirror = true;
      setRotation(tail1, -0.6253236F, 0.6761344F, 0.1115358F);
      tail2 = new ModelRenderer(this, 18, 22);
      tail2.addBox(-0.5F, -0.5F, -1F, 1, 1, 6);
      tail2.setRotationPoint(2F, 15F, 4F);
      tail2.setTextureSize(128, 64);
      tail2.mirror = true;
      setRotation(tail2, -0.1420016F, -0.8110101F, 0.2230717F);
      Fish = new ModelRenderer(this, 18, 18);
      Fish.addBox(0F, -4F, -9F, 0, 14, 14);
      Fish.setRotationPoint(0F, -1F, -8F);
      Fish.setTextureSize(128, 64);
      Fish.mirror = true;
      setRotation(Fish, -0.5205006F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    body.render(f5);
    head.render(f5);
    nose.render(f5);
    leftear.render(f5);
    rightear.render(f5);
    backfeetleft.render(f5);
    backfeetright.render(f5);
    frontLeftPaw.render(f5);
    frontRightPaw.render(f5);
    tail1.render(f5);
    tail2.render(f5);
    Fish.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
